---
title: "SOC 280 LAB Homework 3"
author: "YOUR NAME HERE"
output: html_notebook
---

# Problem 1: Gathering Census Data

For this homework, you'll gather data from the census about US counties. You'll need to get data about race and ethnicity (use the variable names from Lab 9), median income (use B06011_001), and number of people in poverty (use B17001_002). Load the libraries you'll need as you go.

## 1.1 
Create a named vector, like in Lab 9, that has the variable codes as values and descriptive names as names. Print the vector.

## 1.2 
Use the tidycensus package to gather data from the 2021 American Community Survey 5-year estimates (acs5) for all counties in the US. Show the first rows from the raw data.

## 1.3 
Using the code from Lab 9 as a template, modify the ACS data so that it has one row per county, and calculate proportions for each ethnoracial category and for people below the poverty line. Use `glimpse` on this new dataset to show the new columns you've made.

## 1.Bonus
Using the method from Lab 9, find the name code for at least one other variable and include it in your data. Write a sentence or two about why you picked that variable and what it means.

# Problem 2: Plotting Census Data
For all of the plots below, include a clear title, axis labels, and consistent style.

## 2.1 
Make a histogram of the median income from each county. Include a vertical line showing the average county income in red, and a verticle line showing the income for Cook County, IL in blue. Write at least two sentences interpreting the plot.

## 2.2 
Make a scatterplot showing the relationship between any racial group and poverty. Include a trend line showing the linear relationship. Color the dot representing Cook County, IL blue. Write at least two sentences interpreting the plot.

## 2.3 
Make a choropleth map of counties from ONE state that is not Illinois. Color the counties to reflect any variable you've collected. Write at least two sentences interpreting the plot.

## 2.Bonus
Use the variable you gathered in 1.Bonus and one other variable to make a visualization (type of your choice). Write at least two sentences interpreting your plot.
  
# Problem 3: Make the Plots  

## 3.1
*You'll need to have a few plots in your poster. It helps to think about what you want to present and how you'll prepare and present that using your data. You'll plan 3 plots below (they don't all have to be in your final poster). For each, provide:*
  
a. The purpose of the plot: what do you want people to understand when they see this?  
b. The type of plot: what geom functions will you use to present the plot? Why are those the best choices?  
c. Limitations/biases: What is missing from this presentation? Could someone get the wrong idea? What can you do to help limit the negative possibilities here?  

Plot idea 1:  
a.  
b.  
c.  

Plot idea 2:  
a.  
b.  
c.  

Plot idea 3:  
a.  
b.  
c.  

## 3.2
Using your plans from problem 3.1, produce the plots in r. Use as many codeblocks as you need. Make sure to include proper titles and labels. Think about reducing chart junk and improving your data/ink ratio.
  
Plot 1:  
Plot 2:  
Plot 3:  


